# Generated by Django 4.2.1 on 2023-05-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mayor_de_edad', models.CharField(max_length=2)),
                ('sabor_p', models.CharField(max_length=10)),
                ('calidad_p', models.CharField(max_length=10)),
                ('formato_p', models.CharField(max_length=10)),
                ('recomendar_p', models.CharField(max_length=2)),
            ],
        ),
    ]
